export const courses = {
    softwareDevelopment: [{
        id: 1,
        title: 'React Native',
        author: 'Hai Pham',
        level: 'Advance',
        released: 'May 12, 2020',
        duration: '38 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 2,
        title: 'Android',
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '30 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 3,
        title: 'IOS',
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '30 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 4,
        title: 'ReactJs',
        author: 'Hai Pham',
        level: 'Advance',
        released: 'May 12, 2020',
        duration: '38 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 5,
        title: 'VueJs',
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '30 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isPaths: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 6,
        title: 'NuxtJs',
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '30 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 7,
        title: 'Java Developer',
        author: 'Hai Pham',
        level: 'Advance',
        released: 'May 12, 2020',
        duration: '38 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 8,
        title: 'Python',
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '30 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 9,
        title: 'Angular',
        author: 'Huy Nguyen',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '30 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 10,
        title: 'Spring Framework: Spring MVC',
        author: 'Bryan',
        level: 'Beginner',
        released: 'May 15, 2019',
        duration: '23 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 11,
        title: 'Restful API webservice',
        author: 'Shawn',
        level: 'Beginner',
        released: 'Feb 27, 2019',
        duration: '12 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 12,
        title: 'NodeJs: The Big Picture',
        author: 'Fallon',
        level: 'Beginner',
        released: 'Jun 3, 2019',
        duration: '5 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 13,
        title: 'Javascript: Getting Started',
        author: 'Barry',
        level: 'Beginner',
        released: 'Jan 16, 2019',
        duration: '4 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 14,
        title: 'HTML, CSS, Javascript: The Big Picture',
        author: 'Hieu Duong',
        Level: 'Beginner',
        released: 'Jan 20, 2019',
        duration: '1 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 15,
        title: 'C++: The Big Picture',
        author: 'Mike',
        level: 'Beginner',
        released: 'Feb 2, 2020',
        duration: '10 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    }],
    itOperations: [{
        id: 1,
        title: 'Architecting for Reliability on AWS',
        author: 'Hai Pham',
        level: 'Advance',
        released: 'May 12, 2020',
        duration: '8 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 2,
        title: 'Architecting for Security on AWS',
        author: 'Huy Nguyen',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 3,
        title: 'Docker Deep Dive',
        author: 'Huy Nguyen',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 4,
        title: 'Managing Microsoft Azure Subcriptions',
        author: 'Hai Pham',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 5,
        title: 'Windows PowerShell Toolmaking Fundamentals',
        author: 'Adam Bertram',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '2 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 6,
        title: 'Computer Fundamentals: Hardware',
        author: 'Daniel Lachance',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 7,
        title: 'Basic Security Concepts for Cisco Network',
        author: 'Ross Bagurdes',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '1 hours 30m',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 8,
        title: 'Networking Concepts and Protocols',
        author: 'Ross Bagurdes',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '5 hours 20m',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    }],
    securityProfessional: [{
        id: 1,
        title: 'Creating Security Baselines in Microsoft Azure',
        author: 'Neil Morrissey',
        level: 'Advance',
        released: 'May 12, 2020',
        duration: '1 hours 55m',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 2,
        title: 'Malware Analysis: Indentifying and Defeating Code Obfuscation',
        author: 'Josh Stroschein',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 3,
        title: 'Performing Malware Analysis on Malicious Documents',
        author: 'Tyler Hudak',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 4,
        title: 'EthicalHacking: Social Engineering',
        author: 'Kevin Henry',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 5,
        title: 'Security Management',
        author: 'Kevin Henry',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '2 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 6,
        title: 'Investigations and Incident Management',
        author: 'Kevin Henry',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    }],
    dataProofessional: [{
        id: 1,
        title: 'Python: The Big Picture',
        author: 'Jason Olson',
        level: 'Advance',
        released: 'May 12, 2020',
        duration: '1 hours 55m',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 2,
        title: 'Google Cloud Platform Big Data and Machine Learning Fundamentals',
        author: 'Google Cloud',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 3,
        title: 'Programming with R',
        author: 'Tyler Hudak',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 4,
        title: 'Building Your First Power BI Report',
        author: 'Kevin Henry',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 5,
        title: 'Getting Started with Your First SQL Server Instance',
        author: 'Kevin Hill',
        level: 'Intermediate',
        released: 'May 12, 2020',
        duration: '2 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    },
    {
        id: 6,
        title: 'Introduction to TensorFlow',
        author: 'Google Cloud',
        level: 'Beginner',
        released: 'May 12, 2020',
        duration: '3 hours',
        star: 5,
        islearning: 0,
        isFavorite: 0,
        isNew: 0,
        isTrending: 0
    }]
}

export const paths = {
    
}